import { createRequire } from 'node:module'; const require = createRequire(import.meta.url);
import { spawn } from 'node:child_process';
import fs from 'node:fs';
const [, , embedder, label] = process.argv;
const root = fs.mkdtempSync('/tmp/memprobe-');
const proc = spawn('node', ['dist/mcp/server.js', '--root', root], { env: { ...process.env, MEM_EMBEDDER: embedder }, stdio: ['pipe', 'pipe', 'pipe'] });
let peak = 0; const samples: number[] = [];
const rss = () => { try { return parseInt(require('node:child_process').execSync(`ps -o rss= -p ${proc.pid}`).toString(), 10) / 1024; } catch { return 0; } };
const timer = setInterval(() => { const r = rss(); samples.push(r); if (r > peak) peak = r; }, 100);
let out = '';
proc.stdout.on('data', (d) => (out += d));
const send = (o: any) => proc.stdin.write(JSON.stringify(o) + '\n');
const waitFor = (id: number) => new Promise<void>((res) => { const t = setInterval(() => { if (out.includes(`"id":${id}`)) { clearInterval(t); res(); } }, 50); });
const t0 = Date.now();
send({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'probe', version: '0' } } });
await waitFor(1);
const afterInit = rss(); const tInit = Date.now() - t0;
send({ jsonrpc: '2.0', method: 'notifications/initialized' });
send({ jsonrpc: '2.0', id: 2, method: 'tools/call', params: { name: 'memory_remember', arguments: { text: 'The staging database lives in region europe-west1.', kind: 'fact' } } });
await waitFor(2);
const afterRemember = rss();
send({ jsonrpc: '2.0', id: 3, method: 'tools/call', params: { name: 'memory_recall', arguments: { text: 'where is staging db', k: 3 } } });
await waitFor(3);
const afterRecall = rss();
await new Promise((r) => setTimeout(r, 1500));
const settled = rss();
clearInterval(timer);
proc.kill();
console.log(JSON.stringify({ label, embedder, initMs: tInit, rssMB: { afterInit: Math.round(afterInit), afterRemember: Math.round(afterRemember), afterRecall: Math.round(afterRecall), settled: Math.round(settled), peak: Math.round(peak) } }));
